version: '3.4'

services:
  energiaeficiente:
    image: ${DOCKER_REGISTRY-}energiaeficiente
    build:
      context: .
      dockerfile: EnergiaEficiente/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    ports:
      - "5000:80"
      #- "5001:443"
    networks:
      - chimiel
  nginx:
    build:
     context: .
     dockerfile: nginx/nginx.Dockerfile
    depends_on:
      - energiaeficiente
    ports:
     - "5100:5100"
     - "5200:5200"
    networks:
      - chimiel
  logseq:
    image: datalust/seq
    restart: unless-stopped
    ports: 
        - "5341:80"
    environment:
        - ACCEPT_EULA=Y
    networks:
      - chimiel
  sql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - "1435:1433"
    networks:
      - chimiel
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Fbi240491
networks:
  chimiel: {}